### ISSUE TITLE
[DOCS] Is it possible to have the instance_service_id and the other id as parameters for the terraform provision and bind script

### ISSUE THREAD

**Issue by wdesplas** [cloudfoundry-incubator/cloud-service-broker#323]
## Documentation Requested 
Hi,

I have tried to find any way to pass the instance_id, the bindind_id to the provision and binding phase. To do it I try to have these if as input for the provision.tf and bind.tf for terraform provisioning with no proper result.

In fact, I got the following error where I use '${request.instance_id}' as parameters:
```
A managed resource \"request\" \"instance_id\" has not been declared in instance.\n\n","request-id":""}}
```
Could you please let me know if is it possible and the way to do it?

Thanks in advance.

Regards,

**Comment by wdesplas** [comment]
Do I have to use this documentation?
https://github.com/cloudfoundry-incubator/cloud-service-broker/blob/0.4.0/docs/brokerpak-specification.md#provisiondeprovision

**Comment by wdesplas** [comment]
I think I got it, 

First we have to add the needed field in the servide definition (yml) as follow. In my case I try to use the instance_id:
```
  # Add instanceid as field name for legacy
  - field_name: instance_id
    type: string
    details: Permanent identifier for your instance
    default: ${request.instance_id}
    constraints:
      maxLength: 30
      minLength: 6
      pattern: ^[a-z][a-z0-9-]+$}
```

Then we can use this values as parameters of the terraform.
