### ISSUE TITLE
[DOCS] : During the an update, there is a possibility to check the parameters 

### ISSUE THREAD

**Issue by wdesplas** [cloudfoundry-incubator/cloud-service-broker#338]
## Documentation Requested 
During an update, the required parameters present in the service-definition is not checked any more.

Do we have a possibility to verified that en fields are presents as parameters before procedeed to the update?

Bellow the output mandatory in the user_inputs that is not checked during an update:
```
provision:
  plan_inputs: []
  user_inputs:
  - required: true
    field_name: x-osb-cmdb
    type: object
    details: x-osb-cmdb
  - required: true
    field_name: dstdomains
    type: array
    details: List of domains to access   
  - required: true
    field_name: source_ips
    type: array
    details: List of your machines ip's
  - required: true
    field_name: security_group
    type: string
    details: Your security group
```

Thanks in advance.

Regards,
